# Generated by Django 5.0.6 on 2026-09-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='quiz_attempts', to='learning.topic'),
        ),
    ]
