from django import forms
from apps.accounts.forms import StyledFormMixin
from apps.learning.models import Course, Topic


class QuizGenerateForm(StyledFormMixin, forms.Form):
    DIFFICULTY_CHOICES = [('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')]
    difficulty = forms.ChoiceField(choices=DIFFICULTY_CHOICES, initial='Medium')
    num_questions = forms.IntegerField(min_value=3, max_value=25, initial=10)


class QuizSectionForm(StyledFormMixin, forms.Form):
    DIFFICULTY_CHOICES = [('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')]
    course = forms.ModelChoiceField(queryset=Course.objects.none(), label='Course')
    topics = forms.ModelMultipleChoiceField(queryset=Topic.objects.none(), label='Topics')
    difficulty = forms.ChoiceField(choices=DIFFICULTY_CHOICES, initial='Medium')
    num_questions = forms.IntegerField(min_value=3, max_value=25, initial=10)

    def __init__(self, *args, user=None, **kwargs):
        super().__init__(*args, **kwargs)
        if user is not None:
            self.fields['course'].queryset = Course.objects.filter(student=user)
            self.fields['topics'].queryset = Topic.objects.filter(course__student=user)

# Note: manual admin question authoring (QuestionForm) has been removed —
# every Question now belongs to a student-created Topic and is generated by
# apps.ai_engine.mcq_generator via apps.quizzes.services.create_ai_quiz,
# per the "no hardcoded/global content" requirement.
